### ISSUE TITLE
Add a comment does not work in Safari

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5603]
While trying to confirm if https://github.com/exercism/exercism/issues/5039 was fixed it seems I cannot add a comment in Safari at all... which clicking into the comment field the editor [entry panel] entirely disappears. I'm just left with the toolbar.

<img width="625" alt="Screen Shot 2021-08-31 at 2 12 54 AM" src="https://user-images.githubusercontent.com/6473/131451347-c1584ed8-8cbf-467d-b4a1-ee90ae11873f.png">
<img width="595" alt="Screen Shot 2021-08-31 at 2 12 58 AM" src="https://user-images.githubusercontent.com/6473/131451355-96f639be-625f-40af-aefe-c5ab585889eb.png">

On Mac OS Mojave 10.14, latest Safari.

**Comment by angelikatyborska** [comment]
I _think_ this was fixed (https://github.com/exercism/v3-beta/issues/317 https://github.com/exercism/website/pull/1561/files) but Jeremy stopped deploying recent changes to exercism.lol.

**Comment by joshgoebel** [comment]
Ah... then we'll see post-launch I suppose?

**Comment by iHiD** [comment]
Yeah. Pls check v3-beta for these issues still. Thanks both.

**Comment by iHiD** [comment]
Closing for now. Reopen if still a problem at launch :+1:
