### ISSUE TITLE
Community solutions code can be cut off

### ISSUE THREAD

**Issue by sevenseacat** [exercism/exercism#5761]
eg. on https://exercism.org/tracks/elixir/exercises/two-fer/solutions - 

<img width="448" alt="Screen Shot 2021-09-04 at 4 39 43 pm" src="https://user-images.githubusercontent.com/543859/132088593-18e4e94c-ab1d-479a-9ada-93da58383314.png">

All of the code snippets for this problem get cut off at the same point - at a string interpolation point (`"One for #{name},..."`) and the code gets picked up again at the end of the line. The React component for this might need to escape the snippets or something similar.

**Comment by angelikatyborska** [comment]
Hi! The root cause of this problem has been fixed in https://github.com/exercism/snippet-extractor/pull/32 and we're now waiting for @iHiD to do those two tickets:
- https://github.com/exercism/v3-beta/issues/355
- https://github.com/exercism/v3-beta/issues/361

**Comment by iHiD** [comment]
@angelikatyborska @ErikSchierboom Guessing this can be closed?

**Comment by ErikSchierboom** [comment]
@iHiD It can't yet, We not reprocessed the Elixir solutions apparently (the original example was still wrong). I've just reran the snippet generator for just that example, and it _did_ fix it. To fix this, we'd have to re-run the snippet generator on all of Elixir's published iterations (around 120_000). I could queue this, but we have to make sure to use the background queue. Let me know when (or how) you'd like to do this.

**Comment by ErikSchierboom** [comment]
@iHiD I've changed it slightly because:

a) `solution` doesn't have a `track`, but `exercise` does
b) we can filter the solutions by `status: :published`

My script now looks like this:

```ruby
Solution.published.joins(:exercise).where(exercise: {track_id: Track.find_by(slug: 'elixir')}).find_each do |s|
    GenerateIterationSnippetJob.perform_later(s.published_iterations.last)
end
```

**Comment by iHiD** [comment]
Great! Do it :)

**Comment by ErikSchierboom** [comment]
We've just reprocessed all of Elixir's published iterations, and it looks like this did indeed fix the issue. See https://exercism.org/tracks/elixir/exercises/two-fer/solutions where there are now no longer any cutoffs.
